version: '3.0'
services:
  cassandra:
    image: cassandra
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_HOST=127.0.0.1:9042
      - CASSANDRA_CLUSTER_NAME=products
#      - CASSANDRA_SEEDS=cassandra-node1